version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1443:1443"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"